---
tower_objects:
  organisations:
    - name: Demo
      description: The main Demo organisations
      credential:
        - name: Demo Credential
          username: ansible
          ssh_key_data: "{{ lookup('file', '../vars/ansible_user_ssh_key') }}"
          credential_type: Machine
      projects:
        - name: tower-config-as-code
          description: "A project for tower config as code"
          scm_url: "https://github.com/Tompage1994/tower_config_as_code.git"
          scm_type: git
          scm_update_on_launch: yes
      inventory:
        - name: AWS Environment
          description: Inventory for machines in AWS environment
      inventory_source:
        - name: working demo sources
          description: working demo sources
          source: scm
          source_project: tower-config-as-code
          source_path: vars/inventory
          inventory: AWS Environment

