---
- hosts: tower
  user: ansible
  vars_files:
    - "../vars/base_config.yml"
  collections:
    - awx.awx
  tasks:
    - include_role:
        name: ansible-tower-manage
        tasks_from: "{{tower_tasks}}.yml"
      loop:
        - tower_orgs
        - tower_credential
        - tower_project
        - tower_inventory
        - tower_inventory_source
      loop_control:
        loop_var: tower_tasks
      vars:
        tower_manage_server: "https://localhost"
        tower_manage_validate_certs: false
        tower_manage_username: admin
        tower_manage_password: password

    - name: Copy certs into place
      become: true
      copy:
        src: ../tower.cert
        dest: /etc/tower/tower.cert
      tags:
        - tower_certs

    - name: Copy cert key into place
      become: true
      copy:
        src: ../tower.key
        dest: /etc/tower/tower.key
      tags:
        - tower_certs

    - name: Restart Ansible tower service
      become: true
      command: ansible-tower-service restart
      tags:
        - tower_certs