---
- hosts: tower
  user: ansible
  vars_files:
    - "../vars/base_config.yml"
  collections:
    - redhat-cop.tower_configuration
  roles:
    - organizations
    - credentials
    - projects
    - inventories
    - inventory_sources
