---
- hosts: localhost
  collections:
    - tompage1994.tower_configuration
  vars:
    tower_hostname: https://tower.tompage.dev
    validate_certs: false
    tower_username: admin
    tower_password: r3dh4t!
  tasks:
    - name: "Include {{ tower_tasks }} role"
      include_role:
        name: "{{ tower_tasks }}"
      loop: "{{ tower_object_types }}"
      loop_control:
        loop_var: tower_tasks
